// UI strings. Only Russian for now; kept in one place so EPIC 36 can add English.
export const t = {
  appName: "Квиз для своих",
  tagline: "Вопросы, которые собираются под вашу компанию",
  createRoom: "Создать игру",
  creating: "Создаём…",
  haveCode: "Есть код комнаты?",
  join: "Войти",
  roomCode: "Код комнаты",
  yourName: "Как тебя зовут?",
  namePlaceholder: "Имя для этой игры",
  joining: "Входим…",
  scanToJoin: "Сканируй, чтобы играть",
  orOpen: "или открой",
  andEnterCode: "и введи код",
  players: "Игроки",
  noPlayersYet: "Пока никого — сканируйте QR-код",
  hostHint: "Кто войдёт первым, тот и управляет игрой",
  host: "ведущий",
  offline: "не в сети",
  waitingForHost: "Ждём, когда ведущий начнёт",
  youAreHost: "Ты управляешь игрой",
  start: "Начать",
  needTwoPlayers: "Нужно минимум 2 игрока",
  answered: (n: number, total: number) => `Ответили ${n} из ${total}`,
  answerAccepted: "Ответ принят",
  waitForOthers: "Ждём остальных",
  revealNow: "Показать ответ",
  correct: "Верно!",
  wrong: "Мимо",
  noAnswer: "Ты не успел ответить",
  correctAnswer: "Правильный ответ",
  nextDemo: "Ещё раз (демо)",
  lookAtScreen: "Смотри на общий экран",
  reconnecting: "Связь потеряна. Переподключаемся…",
  roomNotFound: "Комната не найдена. Проверь код.",
  sessionExpired: "Сессия устарела — войди заново.",
  displayNoToken: "Этот экран открыт без ключа комнаты. Создай игру заново на этом устройстве.",
  errorGeneric: "Что-то пошло не так. Попробуй ещё раз.",
  question: (n: number) => `Вопрос ${n}`,
};
