// UI strings. Only Russian for now; kept in one place so EPIC 36 can add English.
const nf = new Intl.NumberFormat("ru-RU");

export const t = {
  appName: "Квиз для своих",
  tagline: "Вопросы, которые собираются под вашу компанию",
  createRoom: "Создать игру",
  creating: "Создаём…",
  haveCode: "Есть код комнаты?",
  join: "Войти",
  roomCode: "Код комнаты",
  yourName: "Как тебя зовут?",
  namePlaceholder: "Имя для этой игры",
  joining: "Входим…",
  scanToJoin: "Сканируй, чтобы играть",
  orOpen: "или открой",
  andEnterCode: "и введи код",
  players: "Игроки",
  noPlayersYet: "Пока никого — сканируйте QR-код",
  hostHint: "Кто войдёт первым, тот и управляет игрой",
  host: "ведущий",
  offline: "не в сети",
  waitingForHost: "Ждём, когда ведущий начнёт",
  youAreHost: "Ты управляешь игрой",
  start: "Начать",
  needTwoPlayers: "Нужно минимум 2 игрока",
  question: (n: number) => `Вопрос ${n}`,
  reading: "Читаем вопрос…",
  answered: (n: number, total: number) => `Ответили ${n} из ${total}`,
  answerAccepted: "Ответ принят",
  waitForOthers: "Ждём остальных",
  correct: "Верно!",
  wrong: "Мимо",
  noAnswer: "Не успел ответить",
  correctAnswer: "Правильный ответ",
  points: (n: number) => `+${nf.format(n)}`,
  total: (n: number) => `Всего: ${nf.format(n)}`,
  nextQuestion: "Следующий вопрос…",
  skipped: "Вопрос пропущен",
  paused: "Пауза",
  pause: "Пауза",
  resume: "Продолжить",
  skip: "Пропустить",
  end: "Закончить",
  confirmEnd: "Точно закончить?",
  softEnd: "Прошло полчаса. Закончить игру?",
  softEndContinue: "Играем дальше",
  pendingJoin: "Ты в игре со следующего вопроса",
  lookAtScreen: "Смотри на общий экран",
  results: "Итоги",
  winner: "Победитель",
  score: (n: number) => nf.format(n),
  correctOf: (c: number, a: number) => `${c} из ${a}`,
  yourPlace: (place: number, of: number) => `Твоё место: ${place} из ${of}`,
  playAgain: "Сыграть ещё",
  waitPlayAgain: "Ведущий может начать новую игру",
  questionsPlayed: (n: number) => `Сыграно вопросов: ${n}`,
  statHardest: "Самый сложный вопрос",
  statEveryone: "Это знали все",
  statDivided: "Мнения разделились",
  statOnlyOne: "Это знал только один",
  statFastest: "Самый быстрый верный ответ",
  seconds: (ms: number) => `${(ms / 1000).toLocaleString("ru-RU", { maximumFractionDigits: 1 })} с`,
  reconnecting: "Связь потеряна. Переподключаемся…",
  roomNotFound: "Комната не найдена. Проверь код.",
  displayNoToken: "Этот экран открыт без ключа комнаты. Создай игру заново на этом устройстве.",
  errorGeneric: "Что-то пошло не так. Попробуй ещё раз.",
};
