// UI strings. Only Russian for now; kept in one place so EPIC 36 can add English.
const nf = new Intl.NumberFormat("ru-RU");

export const t = {
  appName: "Квиз для своих",
  tagline: "Вопросы, которые собираются под вашу компанию",
  createRoom: "Создать игру",
  creating: "Создаём…",
  haveCode: "Есть код комнаты?",
  join: "Войти",
  roomCode: "Код комнаты",
  yourName: "Как тебя зовут?",
  namePlaceholder: "Имя для этой игры",
  joining: "Входим…",
  scanToJoin: "Сканируй, чтобы играть",
  orOpen: "или открой",
  andEnterCode: "и введи код",
  players: "Игроки",
  noPlayersYet: "Пока никого — сканируйте QR-код",
  hostHint: "Кто войдёт первым, тот и управляет игрой",
  host: "ведущий",
  offline: "не в сети",
  waitingForHost: "Ждём, когда ведущий начнёт",
  youAreHost: "Ты управляешь игрой",
  start: "Начать",
  needTwoPlayers: "Нужно минимум 2 готовых игрока",
  question: (n: number) => `Вопрос ${n}`,
  reading: "Читаем вопрос…",
  answered: (n: number, total: number) => `Ответили ${n} из ${total}`,
  answerAccepted: "Ответ принят",
  waitForOthers: "Ждём остальных",
  correct: "Верно!",
  wrong: "Мимо",
  noAnswer: "Не успел ответить",
  correctAnswer: "Правильный ответ",
  points: (n: number) => `+${nf.format(n)}`,
  total: (n: number) => `Всего: ${nf.format(n)}`,
  nextQuestion: "Следующий вопрос…",
  skipped: "Вопрос пропущен",
  paused: "Пауза",
  pause: "Пауза",
  resume: "Продолжить",
  skip: "Пропустить",
  end: "Закончить",
  confirmEnd: "Точно закончить?",
  softEnd: "Прошло полчаса. Закончить игру?",
  softEndContinue: "Играем дальше",
  pendingJoin: "Ты в игре со следующего вопроса",
  lookAtScreen: "Смотри на общий экран",
  results: "Итоги",
  winner: "Победитель",
  score: (n: number) => nf.format(n),
  correctOf: (c: number, a: number) => `${c} из ${a}`,
  yourPlace: (place: number, of: number) => `Твоё место: ${place} из ${of}`,
  playAgain: "Сыграть ещё",
  waitPlayAgain: "Ведущий может начать новую игру",
  questionsPlayed: (n: number) => `Сыграно вопросов: ${n}`,
  statHardest: "Самый сложный вопрос",
  statEveryone: "Это знали все",
  statDivided: "Мнения разделились",
  statOnlyOne: "Это знал только один",
  statFastest: "Самый быстрый верный ответ",
  seconds: (ms: number) => `${(ms / 1000).toLocaleString("ru-RU", { maximumFractionDigits: 1 })} с`,
  // onboarding
  back: "Назад",
  cancel: "Отмена",
  next: "Дальше",
  stepOf: (i: number, n: number) => `Шаг ${i} из ${n}`,
  privateNote: "Твои ответы видишь только ты",
  ageTitle: "Сколько тебе лет?",
  ageBand: { "13_17": "13–17", "18_24": "18–24", "25_34": "25–34", "35_44": "35–44", "45_54": "45–54", "55_PLUS": "55+" },
  topicsTitle: "Что тебе интересно?",
  topicsHint: (max: number) => `Лучше 3–7 тем, максимум ${max}. Чем точнее, тем больше вопросов «про тебя».`,
  nextWithCount: (n: number) => `Дальше · ${n}`,
  pickOne: "Выбери хотя бы одну тему",
  depthTitle: "Насколько хорошо ты в этом разбираешься?",
  depth: { CASUAL: "Немного", INTERESTED: "Люблю", EXPERT: "Знаток" },
  lessTitle: "Чего хочется поменьше?",
  lessHint: "Эти темы будут попадаться реже, но не исчезнут совсем.",
  skipStep: "Пропустить",
  backgroundTitle: "В какой культуре прошли твои детство и юность?",
  backgroundHint: "Можно выбрать несколько или пропустить.",
  background: {
    POST_SOVIET: "Постсоветское пространство",
    UK: "Великобритания",
    US: "США",
    EUROPE: "Европа",
    ASIA: "Азия",
  },
  dignityTitle: "Какой квиз тебе по душе?",
  dignity: {
    CLASSIC: { title: "Больше классики", hint: "история, наука, литература, искусство" },
    BALANCE: { title: "Всего понемногу", hint: "и серьёзное, и поп-культура" },
    POP: { title: "Больше поп-культуры и ностальгии", hint: "хиты, сериалы, реклама, мемы" },
  },
  editPrefs: "Изменить интересы",
  readyCount: (r: number, n: number) => `Готовы ${r} из ${n}`,
  chipOnboarding: "заполняет…",
  stragglersHint: "Кто не успел — подключится со следующего вопроса",
  readyWait: "Готово! Ждём начала",

  // offboarding
  feedbackTitle: "Как тебе игра?",
  fbPlayAgain: "Хочется сыграть ещё?",
  fbDifferentGroup: "А с другой компанией?",
  intent: { YES: "Да", MAYBE: "Может быть", NO: "Нет" } as Record<string, string>,
  fbDifficulty: "Сложность",
  fbDifficultyValues: { TOO_EASY: "Легко", JUST_RIGHT: "В самый раз", TOO_HARD: "Сложно" } as Record<string, string>,
  fbPace: "Темп",
  fbPaceValues: { TOO_SLOW: "Медленно", JUST_RIGHT: "В самый раз", TOO_FAST: "Быстро" } as Record<string, string>,
  fbBalance: "Темы",
  fbBalanceValues: { MORE_CLASSIC: "Больше классики", JUST_RIGHT: "В самый раз", MORE_POP: "Больше поп-культуры" } as Record<string, string>,
  fbNeedPlayAgain: "Ответь на первый вопрос",
  send: "Отправить",
  feedbackThanks: "Спасибо! Это помогает делать квиз лучше.",
  rateTitle: "Оцени вопросы",
  rateHint: "Плохие вопросы уйдут на доработку.",
  rating: {
    GREAT: { icon: "👍", label: "Отличный вопрос" },
    FINE: { icon: "👌", label: "Нормальный вопрос" },
    BAD: { icon: "👎", label: "Плохой вопрос" },
  },

  reconnecting: "Связь потеряна. Переподключаемся…",
  roomNotFound: "Комната не найдена. Проверь код.",
  displayNoToken: "Этот экран открыт без ключа комнаты. Создай игру заново на этом устройстве.",
  errorGeneric: "Что-то пошло не так. Попробуй ещё раз.",
};
