// Builds dist/bank.json (APPROVED + GOLD only) and dist/coverage.md (all statuses).
import { mkdirSync, writeFileSync } from "node:fs";
import {
  checkContent,
  PLAYABLE_STATUSES,
  STATUSES,
  type Question,
} from "../../packages/content-schema/src/index.ts";
import { loadFamilies, loadTaxonomy } from "./lib/load.ts";

const taxonomy = loadTaxonomy();
const { files, schemaErrors } = loadFamilies();
const errors = [...schemaErrors, ...checkContent(files, taxonomy).filter((i) => i.level === "error")];
if (errors.length > 0) {
  console.error(`Build aborted: ${errors.length} validation errors. Run npm run content:validate.`);
  process.exit(1);
}

type Row = Question & { fact_id: string; family_id: string };
const rows: Row[] = files.flatMap((f) =>
  f.families.flatMap((family) =>
    family.facts.flatMap((fact) =>
      fact.questions.map((q) => ({ ...q, fact_id: fact.id, family_id: family.family })),
    ),
  ),
);

const playable = rows.filter((q) => (PLAYABLE_STATUSES as readonly string[]).includes(q.status));
const bank = {
  built_at: new Date().toISOString(),
  questions: playable.map(({ review_notes, reviewed, generation_method, editor_rating, ...q }) => q),
};

// ---------- coverage ----------

const primaryTopic = (q: Question) =>
  Object.entries(q.topics).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "—";
const count = <T>(items: T[], key: (x: T) => string) => {
  const m = new Map<string, number>();
  for (const x of items) m.set(key(x), (m.get(key(x)) ?? 0) + 1);
  return m;
};

const lines: string[] = [
  "# Content coverage",
  "",
  `Generated by \`npm run content:build\`. Playable = APPROVED + GOLD. Total questions in files: ${rows.length}, playable: ${playable.length}.`,
  "",
  "## By status",
  "",
  "| Status | Questions |",
  "|---|---|",
  ...STATUSES.map((s) => `| ${s} | ${rows.filter((q) => q.status === s).length} |`),
  "",
  "## By topic (primary topic)",
  "",
  "| Topic | Level | Target | All | Playable | D1 | D2 | D3 | D4 | D5 | Dignity ≤2 | Dignity ≥4 |",
  "|---|---|---|---|---|---|---|---|---|---|---|---|",
];
for (const t of taxonomy.topics) {
  const all = rows.filter((q) => primaryTopic(q) === t.slug);
  const play = all.filter((q) => playable.includes(q));
  const byDiff = count(all, (q) => String(q.difficulty));
  const gap = play.length < t.target_questions ? " ⚠️" : "";
  lines.push(
    `| ${t.slug} | ${t.level} | ${t.target_questions} | ${all.length} | ${play.length}${gap} | ` +
      [1, 2, 3, 4, 5].map((d) => byDiff.get(String(d)) ?? 0).join(" | ") +
      ` | ${all.filter((q) => q.dignity <= 2).length} | ${all.filter((q) => q.dignity >= 4).length} |`,
  );
}

const eras = count(rows.flatMap((q) => Object.keys(q.generations)), (e) => e);
lines.push("", "## By generation tag (all statuses)", "", "| Era | Questions |", "|---|---|");
for (const [era, n] of [...eras].sort()) lines.push(`| ${era} | ${n} |`);

mkdirSync("dist", { recursive: true });
writeFileSync("dist/bank.json", JSON.stringify(bank, null, 2));
writeFileSync("dist/coverage.md", lines.join("\n") + "\n");
console.log(`dist/bank.json: ${playable.length} playable questions; dist/coverage.md: ${rows.length} total`);
