// GENERATED by scripts/dev/gen-shared.ts — do not edit.
import type { BankQuestion } from "./bank.ts";

export const BANK: BankQuestion[] = [
  {
    "id": "tatu-eurovision-2003-place-ru-1",
    "factId": "tatu-eurovision-2003-place",
    "familyId": "tatu",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какое место заняла группа t.A.T.u. на «Евровидении-2003» с песней «Не верь, не бойся»?",
    "options": [
      {
        "key": "A",
        "text": "Первое"
      },
      {
        "key": "B",
        "text": "Третье"
      },
      {
        "key": "C",
        "text": "Второе"
      },
      {
        "key": "D",
        "text": "Девятое"
      }
    ],
    "correctKey": "B",
    "explanation": "Россия набрала 164 балла — всего на 3 меньше победительницы, Сертаб Эренер из Турции.",
    "topics": {
      "ru-pop-00s": 1,
      "eurovision": 0.6
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 2,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 0.8,
      "SHARED_KNOWLEDGE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "tatu-members-ru-1",
    "factId": "tatu-members",
    "familyId": "tatu",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Юлия Волкова пела в группе t.A.T.u. вместе с…",
    "options": [
      {
        "key": "A",
        "text": "Юлией Савичевой"
      },
      {
        "key": "B",
        "text": "Ириной Дубцовой"
      },
      {
        "key": "C",
        "text": "Еленой Катиной"
      },
      {
        "key": "D",
        "text": "Полиной Гагариной"
      }
    ],
    "correctKey": "C",
    "explanation": "Дуэт собрали в 1999 году; обе участницы до этого пели в детском ансамбле «Непоседы».",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 2,
    "effects": {
      "SHARED_KNOWLEDGE": 0.7,
      "WHY_DO_I_REMEMBER_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "tatu-producer-ru-1",
    "factId": "tatu-producer",
    "familyId": "tatu",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто был продюсером и автором концепции группы t.A.T.u.?",
    "options": [
      {
        "key": "A",
        "text": "Юрий Айзеншпис"
      },
      {
        "key": "B",
        "text": "Максим Фадеев"
      },
      {
        "key": "C",
        "text": "Игорь Крутой"
      },
      {
        "key": "D",
        "text": "Иван Шаповалов"
      }
    ],
    "correctKey": "D",
    "explanation": "До t.A.T.u. Шаповалов работал психологом и в рекламе — отсюда провокационный имидж группы.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 4,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "fabrika-zvezd-channel-ru-1",
    "factId": "fabrika-zvezd-channel",
    "familyId": "fabrika-zvezd",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "На каком телеканале выходила первая «Фабрика звёзд» (2002)?",
    "options": [
      {
        "key": "A",
        "text": "Первый канал"
      },
      {
        "key": "B",
        "text": "НТВ"
      },
      {
        "key": "C",
        "text": "СТС"
      },
      {
        "key": "D",
        "text": "Муз-ТВ"
      }
    ],
    "correctKey": "A",
    "explanation": "Продюсером первого сезона был Игорь Матвиенко — тот самый, что стоял за «Любэ» и «Иванушками».",
    "topics": {
      "ru-pop-00s": 1,
      "ru-tv-90s-00s": 0.7
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 1,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 0.8,
      "SHARED_KNOWLEDGE": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "fabrika-zvezd-1-winner-ru-1",
    "factId": "fabrika-zvezd-1-winner",
    "familyId": "fabrika-zvezd",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какой коллектив победил в первой «Фабрике звёзд»?",
    "options": [
      {
        "key": "A",
        "text": "«Банда»"
      },
      {
        "key": "B",
        "text": "«Корни»"
      },
      {
        "key": "C",
        "text": "«Фабрика»"
      },
      {
        "key": "D",
        "text": "«Челси»"
      }
    ],
    "correctKey": "B",
    "explanation": "Их «Ты узнаешь её» стала одним из главных хитов 2002 года. Группа «Фабрика» тоже вышла из первого сезона, но не победила.",
    "topics": {
      "ru-pop-00s": 1,
      "ru-tv-90s-00s": 0.6
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 1,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 1,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "fabrika-zvezd-host-ru-1",
    "factId": "fabrika-zvezd-host",
    "familyId": "fabrika-zvezd",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто вела первые сезоны «Фабрики звёзд»?",
    "options": [
      {
        "key": "A",
        "text": "Ксения Собчак"
      },
      {
        "key": "B",
        "text": "Тина Канделаки"
      },
      {
        "key": "C",
        "text": "Яна Чурикова"
      },
      {
        "key": "D",
        "text": "Ольга Шелест"
      }
    ],
    "correctKey": "C",
    "explanation": "Ксения Собчак в те же годы вела другое большое реалити — «Дом-2» на ТНТ.",
    "topics": {
      "ru-pop-00s": 0.8,
      "ru-tv-90s-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 1,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "fabrika-zvezd-format-ru-1",
    "factId": "fabrika-zvezd-format",
    "familyId": "fabrika-zvezd",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Адаптацией какого международного телеформата была «Фабрика звёзд»?",
    "options": [
      {
        "key": "A",
        "text": "Pop Idol"
      },
      {
        "key": "B",
        "text": "Big Brother"
      },
      {
        "key": "C",
        "text": "Star Academy"
      },
      {
        "key": "D",
        "text": "The X Factor"
      }
    ],
    "correctKey": "C",
    "explanation": "Pop Idol в России адаптировали как «Народный артист» — он шёл в те же годы на канале «Россия».",
    "topics": {
      "ru-pop-00s": 0.7,
      "ru-tv-90s-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1,
      "GLOBAL": 0.3
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 4,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "I_FIGURED_IT_OUT": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "timati-banda-ru-1",
    "factId": "timati-banda",
    "familyId": "timati",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "В составе какой группы Тимати участвовал в «Фабрике звёзд»?",
    "options": [
      {
        "key": "A",
        "text": "«Корни»"
      },
      {
        "key": "B",
        "text": "«Банда»"
      },
      {
        "key": "C",
        "text": "«Инь-Ян»"
      },
      {
        "key": "D",
        "text": "«Челси»"
      }
    ],
    "correctKey": "B",
    "explanation": "Это была четвёртая «Фабрика» (2004); сольную карьеру Тимати начал вскоре после проекта.",
    "topics": {
      "ru-pop-00s": 1,
      "ru-tv-90s-00s": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 1,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 1,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "via-gra-founder-ru-1",
    "factId": "via-gra-founder",
    "familyId": "via-gra",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто создал группу «ВИА Гра» и написал большинство её хитов?",
    "options": [
      {
        "key": "A",
        "text": "Валерий Меладзе"
      },
      {
        "key": "B",
        "text": "Максим Фадеев"
      },
      {
        "key": "C",
        "text": "Константин Меладзе"
      },
      {
        "key": "D",
        "text": "Игорь Матвиенко"
      }
    ],
    "correctKey": "C",
    "explanation": "Константин — младший брат Валерия Меладзе; группу он создал вместе с продюсером Дмитрием Костюком.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 2,
    "effects": {
      "SHARED_KNOWLEDGE": 0.6,
      "I_FIGURED_IT_OUT": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "via-gra-first-singer-ru-1",
    "factId": "via-gra-first-singer",
    "familyId": "via-gra",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто из солисток была в «ВИА Гре» с самого основания группы в 2000 году?",
    "options": [
      {
        "key": "A",
        "text": "Вера Брежнева"
      },
      {
        "key": "B",
        "text": "Алёна Винницкая"
      },
      {
        "key": "C",
        "text": "Анна Седокова"
      },
      {
        "key": "D",
        "text": "Альбина Джанабаева"
      }
    ],
    "correctKey": "B",
    "explanation": "Вера Брежнева и Анна Седокова присоединились позже, в 2002 году.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 4,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.7
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "via-gra-name-ru-1",
    "factId": "via-gra-name",
    "familyId": "via-gra",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": true,
    "text": "Название «ВИА Гра» обыгрывает советскую аббревиатуру ВИА. Как она расшифровывается?",
    "options": [
      {
        "key": "A",
        "text": "Всесоюзное информационное агентство"
      },
      {
        "key": "B",
        "text": "Вокально-инструментальный ансамбль"
      },
      {
        "key": "C",
        "text": "Высшая исполнительская академия"
      },
      {
        "key": "D",
        "text": "Всероссийская интерпретация авторов"
      }
    ],
    "correctKey": "B",
    "explanation": "Так в СССР называли разрешённые поп-группы вроде «Песняров» и «Самоцветов».",
    "topics": {
      "ru-pop-00s": 0.8,
      "ussr-everyday": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1
    },
    "generations": {
      "80s": 0.6,
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 2,
    "effects": {
      "I_FIGURED_IT_OUT": 1,
      "BRIDGE": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "serebro-producer-ru-1",
    "factId": "serebro-producer",
    "familyId": "serebro",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто продюсировал группу «Серебро», занявшую 3-е место на «Евровидении-2007»?",
    "options": [
      {
        "key": "A",
        "text": "Максим Фадеев"
      },
      {
        "key": "B",
        "text": "Иван Шаповалов"
      },
      {
        "key": "C",
        "text": "Константин Меладзе"
      },
      {
        "key": "D",
        "text": "Игорь Крутой"
      }
    ],
    "correctKey": "A",
    "explanation": "Song #1 была дебютной песней группы — «Серебро» поехало на конкурс почти никому не известным.",
    "topics": {
      "ru-pop-00s": 1,
      "eurovision": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 0.8
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "dima-bilan-eurovision-2008-ru-1",
    "factId": "dima-bilan-eurovision-2008",
    "familyId": "dima-bilan",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "С какой песней Дима Билан победил на «Евровидении-2008»?",
    "options": [
      {
        "key": "A",
        "text": "Never Let You Go"
      },
      {
        "key": "B",
        "text": "Shady Lady"
      },
      {
        "key": "C",
        "text": "Believe"
      },
      {
        "key": "D",
        "text": "Song #1"
      }
    ],
    "correctKey": "C",
    "explanation": "С Never Let You Go Билан занял второе место в 2006 году, а Shady Lady принесла второе место Ани Лорак в том же 2008-м.",
    "topics": {
      "ru-pop-00s": 1,
      "eurovision": 0.8
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 2,
    "effects": {
      "SHARED_KNOWLEDGE": 0.8,
      "WHY_DO_I_REMEMBER_THIS": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "dima-bilan-real-name-ru-1",
    "factId": "dima-bilan-real-name",
    "familyId": "dima-bilan",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Как на самом деле зовут Диму Билана?",
    "options": [
      {
        "key": "A",
        "text": "Дмитрий Биланов"
      },
      {
        "key": "B",
        "text": "Виктор Белан"
      },
      {
        "key": "C",
        "text": "Дмитрий Белан"
      },
      {
        "key": "D",
        "text": "Виктор Билан"
      }
    ],
    "correctKey": "B",
    "explanation": "Сценическое имя он позже сделал официальным.",
    "topics": {
      "ru-pop-00s": 1,
      "celebrities": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 4,
    "dignity": 1,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "uma2rman-founders-ru-1",
    "factId": "uma2rman-founders",
    "familyId": "uma2rman",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какие братья основали группу Uma2rman?",
    "options": [
      {
        "key": "A",
        "text": "Вадим и Глеб Самойловы"
      },
      {
        "key": "B",
        "text": "Валерий и Константин Меладзе"
      },
      {
        "key": "C",
        "text": "Борис и Константин Бурдаевы"
      },
      {
        "key": "D",
        "text": "Владимир и Сергей Кристовские"
      }
    ],
    "correctKey": "D",
    "explanation": "Название группы отсылает к актрисе Уме Турман. Бурдаевы — это «Братья Грим», Самойловы — «Агата Кристи».",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 4,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "uma2rman-nochnoy-dozor-ru-1",
    "factId": "uma2rman-nochnoy-dozor",
    "familyId": "uma2rman",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Для какого фильма группа Uma2rman записала песню?",
    "options": [
      {
        "key": "A",
        "text": "«Бумер»"
      },
      {
        "key": "B",
        "text": "«Ночной дозор»"
      },
      {
        "key": "C",
        "text": "«Брат 2»"
      },
      {
        "key": "D",
        "text": "«9 рота»"
      }
    ],
    "correctKey": "B",
    "explanation": "Песня так и называется — «Ночной дозор»; фильм Тимура Бекмамбетова вышел в 2004 году.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 0.8,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "zveri-rayony-kvartaly-ru-1",
    "factId": "zveri-rayony-kvartaly",
    "familyId": "zveri",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какая группа исполняла песню «Районы-кварталы»?",
    "options": [
      {
        "key": "A",
        "text": "«Мумий Тролль»"
      },
      {
        "key": "B",
        "text": "«Би-2»"
      },
      {
        "key": "C",
        "text": "«Сплин»"
      },
      {
        "key": "D",
        "text": "«Звери»"
      }
    ],
    "correctKey": "D",
    "explanation": "Песня вышла в середине 2000-х и стала одним из гимнов дворовых компаний того времени.",
    "topics": {
      "ru-pop-00s": 1,
      "ru-rock": 0.4
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 1,
    "dignity": 2,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "zveri-roma-real-name-ru-1",
    "factId": "zveri-roma-real-name",
    "familyId": "zveri",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какая настоящая фамилия у Ромы Зверя, лидера группы «Звери»?",
    "options": [
      {
        "key": "A",
        "text": "Зверев"
      },
      {
        "key": "B",
        "text": "Билык"
      },
      {
        "key": "C",
        "text": "Белый"
      },
      {
        "key": "D",
        "text": "Романов"
      }
    ],
    "correctKey": "B",
    "explanation": "Роман Билык родом из Таганрога; в Москву он переехал уже с готовыми песнями будущих «Зверей».",
    "topics": {
      "ru-pop-00s": 1,
      "ru-rock": 0.4
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 5,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.8
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "seryoga-chorny-bumer-ru-1",
    "factId": "seryoga-chorny-bumer",
    "familyId": "seryoga",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто исполнял песню «Чёрный бумер»?",
    "options": [
      {
        "key": "A",
        "text": "Серёга"
      },
      {
        "key": "B",
        "text": "Тимати"
      },
      {
        "key": "C",
        "text": "Децл"
      },
      {
        "key": "D",
        "text": "Сергей Шнуров"
      }
    ],
    "correctKey": "A",
    "explanation": "Шнуров написал музыку к фильму «Бумер», но «Чёрный бумер» — песня Серёги, к фильму она отношения не имеет.",
    "topics": {
      "ru-pop-00s": 1,
      "music-now": 0.2
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 1,
    "dignity": 1,
    "effects": {
      "SHARED_KNOWLEDGE": 0.8,
      "WHY_DO_I_REMEMBER_THIS": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "glukoza-animated-image-ru-1",
    "factId": "glukoza-animated-image",
    "familyId": "glukoza",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Чем был необычен образ Глюк'oZa в первых клипах (2002–2003)?",
    "options": [
      {
        "key": "A",
        "text": "Певица выступала в маске, скрывая лицо"
      },
      {
        "key": "B",
        "text": "Вместо певицы в клипах был нарисованный персонаж"
      },
      {
        "key": "C",
        "text": "Голос певицы был полностью синтезирован"
      },
      {
        "key": "D",
        "text": "Все песни исполнялись на английском"
      }
    ],
    "correctKey": "B",
    "explanation": "Реальная исполнительница, Наталья Ионова, появилась перед публикой не сразу. Проект продюсировал Максим Фадеев.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 2,
    "dignity": 1,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 1,
      "I_FIGURED_IT_OUT": 0.3
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "mumiy-troll-eurovision-2001-ru-1",
    "factId": "mumiy-troll-eurovision-2001",
    "familyId": "russia-eurovision",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Какая группа представляла Россию на «Евровидении-2001»?",
    "options": [
      {
        "key": "A",
        "text": "«Мумий Тролль»"
      },
      {
        "key": "B",
        "text": "t.A.T.u."
      },
      {
        "key": "C",
        "text": "«Серебро»"
      },
      {
        "key": "D",
        "text": "«Звери»"
      }
    ],
    "correctKey": "A",
    "explanation": "Песня Lady Alpine Blue заняла 12-е место. t.A.T.u. поехали на конкурс двумя годами позже.",
    "topics": {
      "ru-pop-00s": 0.8,
      "eurovision": 1,
      "ru-rock": 0.4
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "I_FIGURED_IT_OUT": 0.3
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "alsu-eurovision-2000-ru-1",
    "factId": "alsu-eurovision-2000",
    "familyId": "russia-eurovision",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "С какой песней Алсу заняла второе место на «Евровидении-2000»?",
    "options": [
      {
        "key": "A",
        "text": "Believe"
      },
      {
        "key": "B",
        "text": "Solo"
      },
      {
        "key": "C",
        "text": "«Зимний сон»"
      },
      {
        "key": "D",
        "text": "Lady Alpine Blue"
      }
    ],
    "correctKey": "B",
    "explanation": "Это было первое второе место России на конкурсе. «Зимний сон» — её же хит, но к «Евровидению» он отношения не имеет.",
    "topics": {
      "ru-pop-00s": 0.8,
      "eurovision": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1,
      "90s": 0.4
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "WHY_DO_I_REMEMBER_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "polina-gagarina-fabrika-2-ru-1",
    "factId": "polina-gagarina-fabrika-2",
    "familyId": "polina-gagarina",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто победил во второй «Фабрике звёзд» (2003), а в 2015 году занял второе место на «Евровидении»?",
    "options": [
      {
        "key": "A",
        "text": "Юлия Савичева"
      },
      {
        "key": "B",
        "text": "Ирина Дубцова"
      },
      {
        "key": "C",
        "text": "Полина Гагарина"
      },
      {
        "key": "D",
        "text": "Елена Темникова"
      }
    ],
    "correctKey": "C",
    "explanation": "На «Евровидении-2015» в Вене Гагарина исполнила песню A Million Voices.",
    "topics": {
      "ru-pop-00s": 1,
      "eurovision": 0.6,
      "ru-tv-90s-00s": 0.4
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1,
      "10s": 0.6
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "I_FIGURED_IT_OUT": 0.6,
      "I_KNOW_THIS": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "smash-members-ru-1",
    "factId": "smash-members",
    "familyId": "smash",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "С кем Сергей Лазарев пел в дуэте Smash!!?",
    "options": [
      {
        "key": "A",
        "text": "С Владом Соколовским"
      },
      {
        "key": "B",
        "text": "С Владом Топаловым"
      },
      {
        "key": "C",
        "text": "С Димой Биланом"
      },
      {
        "key": "D",
        "text": "С Тимати"
      }
    ],
    "correctKey": "B",
    "explanation": "Дуэт прославился кавер-версией песни Belle из мюзикла «Нотр-Дам де Пари». Влад Соколовский — участник «Банды» с «Фабрики».",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 2,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "WHY_DO_I_REMEMBER_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "maksim-znaesh-li-ty-ru-1",
    "factId": "maksim-znaesh-li-ty",
    "familyId": "maksim",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "LOCAL",
    "isBridge": false,
    "text": "Кто исполнял хит середины 2000-х «Знаешь ли ты»?",
    "options": [
      {
        "key": "A",
        "text": "Земфира"
      },
      {
        "key": "B",
        "text": "Юлия Савичева"
      },
      {
        "key": "C",
        "text": "МакSим"
      },
      {
        "key": "D",
        "text": "Ёлка"
      }
    ],
    "correctKey": "C",
    "explanation": "Песня принесла певице из Казани всероссийскую известность.",
    "topics": {
      "ru-pop-00s": 1
    },
    "contexts": {
      "POST_SOVIET": 1,
      "RUSSIA_2000S": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 1,
    "dignity": 2,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "gagarin-spacecraft-ru-1",
    "factId": "gagarin-spacecraft",
    "familyId": "vostok-1",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Как назывался корабль, на котором Юрий Гагарин полетел в космос?",
    "options": [
      {
        "key": "A",
        "text": "«Союз-1»"
      },
      {
        "key": "B",
        "text": "«Восход-1»"
      },
      {
        "key": "C",
        "text": "«Восток-1»"
      },
      {
        "key": "D",
        "text": "«Мир»"
      }
    ],
    "correctKey": "C",
    "explanation": "Полёт состоялся 12 апреля 1961 года; «Восходы» летали позже, в 1964–1965 годах.",
    "topics": {
      "space": 1,
      "ussr-history": 0.4
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.6
    },
    "generations": {},
    "difficulty": 1,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "gagarin-flight-duration-ru-1",
    "factId": "gagarin-flight-duration",
    "familyId": "vostok-1",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Сколько длился полёт Юрия Гагарина?",
    "options": [
      {
        "key": "A",
        "text": "108 минут"
      },
      {
        "key": "B",
        "text": "45 минут"
      },
      {
        "key": "C",
        "text": "Около 5 часов"
      },
      {
        "key": "D",
        "text": "Почти сутки"
      }
    ],
    "correctKey": "A",
    "explanation": "Корабль совершил один виток вокруг Земли; суточный полёт выполнил следующий космонавт, Герман Титов.",
    "topics": {
      "space": 1,
      "ussr-history": 0.3
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.6
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.6,
      "I_FIGURED_IT_OUT": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "korolev-chief-designer-ru-1",
    "factId": "korolev-chief-designer",
    "familyId": "vostok-1",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "REGIONAL",
    "isBridge": false,
    "text": "Кто был главным конструктором советской космической программы во время полёта Гагарина?",
    "options": [
      {
        "key": "A",
        "text": "Константин Циолковский"
      },
      {
        "key": "B",
        "text": "Михаил Янгель"
      },
      {
        "key": "C",
        "text": "Андрей Туполев"
      },
      {
        "key": "D",
        "text": "Сергей Королёв"
      }
    ],
    "correctKey": "D",
    "explanation": "Циолковский — теоретик космонавтики, он умер в 1935 году, за четверть века до полёта Гагарина.",
    "topics": {
      "space": 1,
      "ussr-history": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1,
      "GLOBAL": 0.4
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 0.7,
      "I_FIGURED_IT_OUT": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "tereshkova-callsign-ru-1",
    "factId": "tereshkova-callsign",
    "familyId": "soviet-cosmonauts",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "REGIONAL",
    "isBridge": false,
    "text": "Какой позывной был у Валентины Терешковой, первой женщины в космосе?",
    "options": [
      {
        "key": "A",
        "text": "«Кедр»"
      },
      {
        "key": "B",
        "text": "«Чайка»"
      },
      {
        "key": "C",
        "text": "«Ястреб»"
      },
      {
        "key": "D",
        "text": "«Беркут»"
      }
    ],
    "correctKey": "B",
    "explanation": "Её фраза «Я — Чайка» стала знаменитой. «Кедр» — позывной Гагарина, «Ястреб» — Быковского, летавшего одновременно с ней.",
    "topics": {
      "space": 1,
      "ussr-history": 0.4
    },
    "contexts": {
      "POST_SOVIET": 1,
      "GLOBAL": 0.3
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "WHY_DO_I_REMEMBER_THIS": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "leonov-first-spacewalk-ru-1",
    "factId": "leonov-first-spacewalk",
    "familyId": "soviet-cosmonauts",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Кто первым в истории вышел в открытый космос?",
    "options": [
      {
        "key": "A",
        "text": "Юрий Гагарин"
      },
      {
        "key": "B",
        "text": "Герман Титов"
      },
      {
        "key": "C",
        "text": "Нил Армстронг"
      },
      {
        "key": "D",
        "text": "Алексей Леонов"
      }
    ],
    "correctKey": "D",
    "explanation": "Это случилось в 1965 году. При возвращении скафандр Леонова раздулся, и ему пришлось стравить давление, чтобы влезть обратно в шлюз.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.6
    },
    "generations": {},
    "difficulty": 1,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "polyakov-longest-flight-ru-1",
    "factId": "polyakov-longest-flight",
    "familyId": "soviet-cosmonauts",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Кому принадлежит рекорд самого длинного непрерывного полёта в космосе — около 437 суток?",
    "options": [
      {
        "key": "A",
        "text": "Сергею Крикалёву"
      },
      {
        "key": "B",
        "text": "Скотту Келли"
      },
      {
        "key": "C",
        "text": "Валерию Полякову"
      },
      {
        "key": "D",
        "text": "Геннадию Падалке"
      }
    ],
    "correctKey": "C",
    "explanation": "Поляков, врач по профессии, провёл на станции «Мир» больше года, чтобы проверить, выдержит ли человек полёт к Марсу. У Скотта Келли — 340 суток.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.5
    },
    "generations": {
      "90s": 0.5
    },
    "difficulty": 5,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 1,
      "HERO_CANDIDATE": 0.8
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "belka-strelka-ru-1",
    "factId": "belka-strelka",
    "familyId": "space-dogs",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Как звали собак, которые в 1960 году первыми вернулись живыми с орбиты?",
    "options": [
      {
        "key": "A",
        "text": "Пчёлка и Мушка"
      },
      {
        "key": "B",
        "text": "Белка и Стрелка"
      },
      {
        "key": "C",
        "text": "Дезик и Цыган"
      },
      {
        "key": "D",
        "text": "Чернушка и Звёздочка"
      }
    ],
    "correctKey": "B",
    "explanation": "Все варианты — реальные «собаки-космонавты»: Дезик и Цыган летали на суборбитальной ракете в 1951 году, а Пчёлка и Мушка погибли при возвращении в декабре 1960-го.",
    "topics": {
      "space": 1,
      "ussr-history": 0.3
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.6
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 4,
    "effects": {
      "SHARED_KNOWLEDGE": 0.8,
      "I_FIGURED_IT_OUT": 0.3
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "laika-sputnik-2-ru-1",
    "factId": "laika-sputnik-2",
    "familyId": "space-dogs",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "На каком аппарате в 1957 году полетела в космос собака Лайка?",
    "options": [
      {
        "key": "A",
        "text": "«Спутник-1»"
      },
      {
        "key": "B",
        "text": "«Восток-1»"
      },
      {
        "key": "C",
        "text": "«Луна-2»"
      },
      {
        "key": "D",
        "text": "«Спутник-2»"
      }
    ],
    "correctKey": "D",
    "explanation": "Первый спутник был запущен лишь месяцем раньше и не нёс живых существ; возвращение Лайки конструкцией не предусматривалось.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1,
      "POST_SOVIET": 0.5
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 4,
    "effects": {
      "I_FIGURED_IT_OUT": 0.7,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "sputnik-1-year-ru-1",
    "factId": "sputnik-1-year",
    "familyId": "sputnik-1",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "В каком году был запущен первый искусственный спутник Земли?",
    "options": [
      {
        "key": "A",
        "text": "1955"
      },
      {
        "key": "B",
        "text": "1957"
      },
      {
        "key": "C",
        "text": "1959"
      },
      {
        "key": "D",
        "text": "1961"
      }
    ],
    "correctKey": "B",
    "explanation": "Сигнал «бип-бип» могли поймать радиолюбители по всему миру — с этого запуска принято отсчитывать космическую эру.",
    "topics": {
      "space": 1,
      "cold-war": 0.4
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "apollo-11-collins-ru-1",
    "factId": "apollo-11-collins",
    "familyId": "apollo",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Кто из экипажа «Аполлона-11» так и не ступил на Луну?",
    "options": [
      {
        "key": "A",
        "text": "Нил Армстронг"
      },
      {
        "key": "B",
        "text": "Базз Олдрин"
      },
      {
        "key": "C",
        "text": "Майкл Коллинз"
      },
      {
        "key": "D",
        "text": "Джим Ловелл"
      }
    ],
    "correctKey": "C",
    "explanation": "Коллинз ждал товарищей на орбите в командном модуле. Джим Ловелл — командир «Аполлона-13», который так и не сел на Луну.",
    "topics": {
      "space": 1,
      "cold-war": 0.3
    },
    "contexts": {
      "GLOBAL": 1,
      "US": 0.5
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.6,
      "I_FIGURED_IT_OUT": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "moonwalkers-count-ru-1",
    "factId": "moonwalkers-count",
    "familyId": "apollo",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Сколько человек за всю историю ходили по Луне?",
    "options": [
      {
        "key": "A",
        "text": "2"
      },
      {
        "key": "B",
        "text": "6"
      },
      {
        "key": "C",
        "text": "12"
      },
      {
        "key": "D",
        "text": "24"
      }
    ],
    "correctKey": "C",
    "explanation": "Шесть экспедиций высадились по два астронавта. Всего же к Луне слетали 24 человека — но многие оставались на орбите.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 4,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.8,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "last-moon-landing-year-ru-1",
    "factId": "last-moon-landing-year",
    "familyId": "apollo",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "В каком году люди в последний раз высаживались на Луну?",
    "options": [
      {
        "key": "A",
        "text": "1969"
      },
      {
        "key": "B",
        "text": "1972"
      },
      {
        "key": "C",
        "text": "1975"
      },
      {
        "key": "D",
        "text": "1986"
      }
    ],
    "correctKey": "B",
    "explanation": "Это был «Аполлон-17»; последним по Луне прошёл Юджин Сернан.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 4,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "I_FIGURED_IT_OUT": 0.3
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "largest-planet-ru-1",
    "factId": "largest-planet",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Какая планета — самая большая в Солнечной системе?",
    "options": [
      {
        "key": "A",
        "text": "Сатурн"
      },
      {
        "key": "B",
        "text": "Нептун"
      },
      {
        "key": "C",
        "text": "Уран"
      },
      {
        "key": "D",
        "text": "Юпитер"
      }
    ],
    "correctKey": "D",
    "explanation": "Юпитер массивнее всех остальных планет, вместе взятых, примерно в два с половиной раза.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 1,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 1
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "hottest-planet-ru-1",
    "factId": "hottest-planet",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "На какой планете Солнечной системы самая высокая температура поверхности?",
    "options": [
      {
        "key": "A",
        "text": "Меркурий"
      },
      {
        "key": "B",
        "text": "Венера"
      },
      {
        "key": "C",
        "text": "Марс"
      },
      {
        "key": "D",
        "text": "Юпитер"
      }
    ],
    "correctKey": "B",
    "explanation": "Меркурий ближе к Солнцу, но плотная углекислотная атмосфера Венеры удерживает тепло — около 465 °C днём и ночью.",
    "topics": {
      "space": 1,
      "science": 0.4
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.7,
      "I_KNOW_THIS": 0.6
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "pluto-dwarf-planet-ru-1",
    "factId": "pluto-dwarf-planet",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": true,
    "text": "В каком году Плутон перестал считаться планетой?",
    "options": [
      {
        "key": "A",
        "text": "1996"
      },
      {
        "key": "B",
        "text": "2001"
      },
      {
        "key": "C",
        "text": "2006"
      },
      {
        "key": "D",
        "text": "2012"
      }
    ],
    "correctKey": "C",
    "explanation": "Международный астрономический союз перевёл его в карликовые планеты — и школьные учебники пришлось переписывать.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {
      "00s": 1
    },
    "difficulty": 3,
    "dignity": 4,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 0.6,
      "BRIDGE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "mars-moons-ru-1",
    "factId": "mars-moons",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Как называются спутники Марса?",
    "options": [
      {
        "key": "A",
        "text": "Ио и Европа"
      },
      {
        "key": "B",
        "text": "Титан и Энцелад"
      },
      {
        "key": "C",
        "text": "Фобос и Деймос"
      },
      {
        "key": "D",
        "text": "Харон и Никта"
      }
    ],
    "correctKey": "C",
    "explanation": "Имена означают «страх» и «ужас» — так звали сыновей бога войны Ареса, греческого Марса.",
    "topics": {
      "space": 1,
      "ancient-world": 0.3
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.6,
      "I_FIGURED_IT_OUT": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "saturn-rings-ice-ru-1",
    "factId": "saturn-rings-ice",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Из чего в основном состоят кольца Сатурна?",
    "options": [
      {
        "key": "A",
        "text": "Из частиц водяного льда"
      },
      {
        "key": "B",
        "text": "Из раскалённого газа"
      },
      {
        "key": "C",
        "text": "Из железных метеоритов"
      },
      {
        "key": "D",
        "text": "Из вулканического пепла"
      }
    ],
    "correctKey": "A",
    "explanation": "Частицы — от песчинок до глыб размером с дом; лёд хорошо отражает свет, поэтому кольца такие яркие.",
    "topics": {
      "space": 1,
      "science": 0.3
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.8
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "sunlight-travel-time-ru-1",
    "factId": "sunlight-travel-time",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Сколько примерно идёт свет от Солнца до Земли?",
    "options": [
      {
        "key": "A",
        "text": "Около 8 секунд"
      },
      {
        "key": "B",
        "text": "Около 8 минут"
      },
      {
        "key": "C",
        "text": "Около часа"
      },
      {
        "key": "D",
        "text": "Около суток"
      }
    ],
    "correctKey": "B",
    "explanation": "Если Солнце вдруг погаснет, мы узнаем об этом примерно через восемь минут.",
    "topics": {
      "space": 1,
      "science": 0.5
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.6,
      "SHARED_KNOWLEDGE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "halley-comet-return-ru-1",
    "factId": "halley-comet-return",
    "familyId": "solar-system",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Когда комета Галлея в следующий раз приблизится к Солнцу?",
    "options": [
      {
        "key": "A",
        "text": "В 2034 году"
      },
      {
        "key": "B",
        "text": "В 2048 году"
      },
      {
        "key": "C",
        "text": "В 2061 году"
      },
      {
        "key": "D",
        "text": "В 2086 году"
      }
    ],
    "correctKey": "C",
    "explanation": "Комета возвращается примерно раз в 76 лет; в прошлый раз её видели в 1986 году.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {
      "80s": 0.5
    },
    "difficulty": 4,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.7,
      "I_KNOW_THIS": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "mir-deorbit-ru-1",
    "factId": "mir-deorbit",
    "familyId": "space-stations",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "REGIONAL",
    "isBridge": false,
    "text": "Что стало со станцией «Мир» в 2001 году?",
    "options": [
      {
        "key": "A",
        "text": "Её разобрали, а модули перевезли на МКС"
      },
      {
        "key": "B",
        "text": "Её затопили в Тихом океане"
      },
      {
        "key": "C",
        "text": "Её подняли на высокую орбиту как музей"
      },
      {
        "key": "D",
        "text": "Она сгорела после пожара на борту"
      }
    ],
    "correctKey": "B",
    "explanation": "Станция проработала 15 лет. Пожар на борту действительно был — в 1997 году, но экипаж его потушил.",
    "topics": {
      "space": 1,
      "russia-90s-life": 0.3
    },
    "contexts": {
      "POST_SOVIET": 1,
      "GLOBAL": 0.6
    },
    "generations": {
      "90s": 0.8,
      "00s": 0.6
    },
    "difficulty": 2,
    "dignity": 4,
    "effects": {
      "WHY_DO_I_REMEMBER_THIS": 0.8,
      "I_FIGURED_IT_OUT": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "iss-orbit-period-ru-1",
    "factId": "iss-orbit-period",
    "familyId": "space-stations",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "За сколько примерно МКС делает один виток вокруг Земли?",
    "options": [
      {
        "key": "A",
        "text": "За 10 минут"
      },
      {
        "key": "B",
        "text": "За 90 минут"
      },
      {
        "key": "C",
        "text": "За 12 часов"
      },
      {
        "key": "D",
        "text": "За сутки"
      }
    ],
    "correctKey": "B",
    "explanation": "Экипаж видит около 16 восходов и закатов в сутки.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {
      "current": 0.5
    },
    "difficulty": 3,
    "dignity": 5,
    "effects": {
      "I_FIGURED_IT_OUT": 0.8
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "baikonur-country-ru-1",
    "factId": "baikonur-country",
    "familyId": "space-stations",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "REGIONAL",
    "isBridge": false,
    "text": "В какой стране находится космодром Байконур?",
    "options": [
      {
        "key": "A",
        "text": "В России"
      },
      {
        "key": "B",
        "text": "В Узбекистане"
      },
      {
        "key": "C",
        "text": "В Казахстане"
      },
      {
        "key": "D",
        "text": "В Туркменистане"
      }
    ],
    "correctKey": "C",
    "explanation": "После распада СССР Россия арендует космодром и город при нём у Казахстана.",
    "topics": {
      "space": 1,
      "geography": 0.5
    },
    "contexts": {
      "POST_SOVIET": 1,
      "GLOBAL": 0.5
    },
    "generations": {},
    "difficulty": 2,
    "dignity": 4,
    "effects": {
      "I_FIGURED_IT_OUT": 0.6,
      "SHARED_KNOWLEDGE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "jwst-launch-ru-1",
    "factId": "jwst-launch",
    "familyId": "modern-spaceflight",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Какой космический телескоп запустили в 2021 году как преемника «Хаббла»?",
    "options": [
      {
        "key": "A",
        "text": "«Кеплер»"
      },
      {
        "key": "B",
        "text": "«Джеймс Уэбб»"
      },
      {
        "key": "C",
        "text": "«Спитцер»"
      },
      {
        "key": "D",
        "text": "«Чандра»"
      }
    ],
    "correctKey": "B",
    "explanation": "Телескоп работает в инфракрасном диапазоне и находится в 1,5 млн км от Земли, в точке Лагранжа L2.",
    "topics": {
      "space": 1,
      "science": 0.4
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {
      "current": 1
    },
    "difficulty": 2,
    "dignity": 5,
    "effects": {
      "SHARED_KNOWLEDGE": 0.7
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "crew-dragon-2020-ru-1",
    "factId": "crew-dragon-2020",
    "familyId": "modern-spaceflight",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Как называется корабль SpaceX, впервые доставивший астронавтов на МКС в 2020 году?",
    "options": [
      {
        "key": "A",
        "text": "Starliner"
      },
      {
        "key": "B",
        "text": "Orion"
      },
      {
        "key": "C",
        "text": "Starship"
      },
      {
        "key": "D",
        "text": "Crew Dragon"
      }
    ],
    "correctKey": "D",
    "explanation": "Это был первый с 2011 года запуск астронавтов с территории США. Starliner — конкурирующий корабль Boeing.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1,
      "US": 0.4
    },
    "generations": {
      "current": 1
    },
    "difficulty": 3,
    "dignity": 4,
    "effects": {
      "I_KNOW_THIS": 0.6,
      "I_FIGURED_IT_OUT": 0.4
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  },
  {
    "id": "voyager-1-heliopause-ru-1",
    "factId": "voyager-1-heliopause",
    "familyId": "modern-spaceflight",
    "language": "ru",
    "originLanguage": "ru",
    "cultureSpecificity": "GLOBAL",
    "isBridge": false,
    "text": "Какой аппарат первым вышел в межзвёздное пространство (2012)?",
    "options": [
      {
        "key": "A",
        "text": "«Вояджер-1»"
      },
      {
        "key": "B",
        "text": "«Вояджер-2»"
      },
      {
        "key": "C",
        "text": "«Пионер-10»"
      },
      {
        "key": "D",
        "text": "«Новые горизонты»"
      }
    ],
    "correctKey": "A",
    "explanation": "Аппарат запущен ещё в 1977 году; «Вояджер-2» пересёк ту же границу в 2018-м.",
    "topics": {
      "space": 1
    },
    "contexts": {
      "GLOBAL": 1
    },
    "generations": {
      "10s": 0.5
    },
    "difficulty": 4,
    "dignity": 5,
    "effects": {
      "I_KNOW_THIS": 0.8,
      "HERO_CANDIDATE": 0.5
    },
    "ageSafety": "ALL",
    "status": "DRAFT"
  }
];
