// GENERATED by scripts/dev/gen-shared.ts — do not edit.
import type { TaxonomyTopic, TaxonomyContext } from "./taxonomy.ts";

export const TOPICS: TaxonomyTopic[] = [
  {
    "slug": "ancient-world",
    "name": "Древний мир",
    "emoji": "🏛️",
    "group": "История",
    "impliedContext": null
  },
  {
    "slug": "russia-pre-1917",
    "name": "История России до 1917",
    "emoji": "👑",
    "group": "История",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "ussr-history",
    "name": "СССР: история",
    "emoji": "🏭",
    "group": "История",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "cold-war",
    "name": "Холодная война и XX век",
    "emoji": "🧊",
    "group": "История",
    "impliedContext": null
  },
  {
    "slug": "ussr-everyday",
    "name": "Советский быт",
    "emoji": "🪆",
    "group": "История",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "russia-90s-life",
    "name": "90-е: жизнь и быт",
    "emoji": "📼",
    "group": "История",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "space",
    "name": "Космос",
    "emoji": "🚀",
    "group": "Наука и мир",
    "impliedContext": null
  },
  {
    "slug": "science",
    "name": "Наука и изобретения",
    "emoji": "🔬",
    "group": "Наука и мир",
    "impliedContext": null
  },
  {
    "slug": "geography",
    "name": "География и страны",
    "emoji": "🌍",
    "group": "Наука и мир",
    "impliedContext": null
  },
  {
    "slug": "nature",
    "name": "Животные и природа",
    "emoji": "🐾",
    "group": "Наука и мир",
    "impliedContext": null
  },
  {
    "slug": "russian-literature",
    "name": "Русская литература",
    "emoji": "📖",
    "group": "Литература и искусство",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "world-literature",
    "name": "Мировая литература",
    "emoji": "📚",
    "group": "Литература и искусство",
    "impliedContext": null
  },
  {
    "slug": "art",
    "name": "Живопись и искусство",
    "emoji": "🎨",
    "group": "Литература и искусство",
    "impliedContext": null
  },
  {
    "slug": "soviet-cinema",
    "name": "Советское кино",
    "emoji": "🎞️",
    "group": "Кино и ТВ",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "world-cinema",
    "name": "Голливуд и мировое кино",
    "emoji": "🎬",
    "group": "Кино и ТВ",
    "impliedContext": null
  },
  {
    "slug": "ru-tv-90s-00s",
    "name": "ТВ 90-х и 00-х",
    "emoji": "📺",
    "group": "Кино и ТВ",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "ru-series",
    "name": "Российские сериалы 2000–2010-х",
    "emoji": "🛋️",
    "group": "Кино и ТВ",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "world-series",
    "name": "Мировые сериалы",
    "emoji": "🍿",
    "group": "Кино и ТВ",
    "impliedContext": null
  },
  {
    "slug": "cartoons",
    "name": "Мультфильмы: советские и мировые",
    "emoji": "🐻",
    "group": "Кино и ТВ",
    "impliedContext": null
  },
  {
    "slug": "ads-90s-00s",
    "name": "Реклама 90-х и 00-х",
    "emoji": "📢",
    "group": "Кино и ТВ",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "ru-pop-90s",
    "name": "Русская поп-музыка 90-х",
    "emoji": "💿",
    "group": "Музыка",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "ru-pop-00s",
    "name": "Русская поп-музыка 00-х",
    "emoji": "🎤",
    "group": "Музыка",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "ru-rock",
    "name": "Русский рок",
    "emoji": "🎸",
    "group": "Музыка",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "world-pop",
    "name": "Мировая поп-музыка 80–00-х",
    "emoji": "🎧",
    "group": "Музыка",
    "impliedContext": null
  },
  {
    "slug": "eurovision",
    "name": "Евровидение",
    "emoji": "🌟",
    "group": "Музыка",
    "impliedContext": null
  },
  {
    "slug": "music-now",
    "name": "Рэп и современная музыка",
    "emoji": "🎙️",
    "group": "Музыка",
    "impliedContext": null
  },
  {
    "slug": "old-internet",
    "name": "Старый интернет",
    "emoji": "💾",
    "group": "Интернет и игры",
    "impliedContext": "POST_SOVIET"
  },
  {
    "slug": "internet-now",
    "name": "Мемы и интернет сейчас",
    "emoji": "📱",
    "group": "Интернет и игры",
    "impliedContext": null
  },
  {
    "slug": "videogames",
    "name": "Видеоигры",
    "emoji": "🎮",
    "group": "Интернет и игры",
    "impliedContext": null
  },
  {
    "slug": "fandoms",
    "name": "Фэнтези и фандомы",
    "emoji": "🧙",
    "group": "Интернет и игры",
    "impliedContext": null
  },
  {
    "slug": "food",
    "name": "Еда и кухня",
    "emoji": "🍲",
    "group": "Жизнь",
    "impliedContext": null
  },
  {
    "slug": "fashion-brands",
    "name": "Мода и бренды",
    "emoji": "👗",
    "group": "Жизнь",
    "impliedContext": null
  },
  {
    "slug": "celebrities",
    "name": "Знаменитости и светская хроника",
    "emoji": "📸",
    "group": "Жизнь",
    "impliedContext": null
  },
  {
    "slug": "football",
    "name": "Футбол",
    "emoji": "⚽",
    "group": "Жизнь",
    "impliedContext": null
  },
  {
    "slug": "sports",
    "name": "Олимпиады, F1 и другой спорт",
    "emoji": "🏅",
    "group": "Жизнь",
    "impliedContext": null
  }
];

export const CONTEXTS: TaxonomyContext[] = [
  {
    "code": "GLOBAL",
    "name": "Глобальный",
    "parent": null
  },
  {
    "code": "POST_SOVIET",
    "name": "Постсоветское пространство",
    "parent": null
  },
  {
    "code": "RUSSIA_1990S",
    "name": "Россия 1990-х",
    "parent": "POST_SOVIET"
  },
  {
    "code": "RUSSIA_2000S",
    "name": "Россия 2000-х",
    "parent": "POST_SOVIET"
  },
  {
    "code": "UK",
    "name": "Великобритания",
    "parent": null
  },
  {
    "code": "US",
    "name": "США",
    "parent": null
  },
  {
    "code": "EUROPE",
    "name": "Европа",
    "parent": null
  },
  {
    "code": "ASIA",
    "name": "Азия",
    "parent": null
  },
  {
    "code": "INTERNET_GLOBAL",
    "name": "Глобальный интернет",
    "parent": null
  }
];
