// Generates code in packages/shared from content/ so the worker and the web app share one source:
//   - taxonomy.generated.ts — topics and cultural contexts for onboarding and validation
//   - demo-bank.generated.ts — questions incl. DRAFTs, a dev-only stand-in for the Composition Engine (M4)
//
//   node scripts/dev/gen-shared.ts
import { writeFileSync } from "node:fs";
import { loadFamilies, loadTaxonomy } from "../content/lib/load.ts";

const HEADER = "// GENERATED by scripts/dev/gen-shared.ts — do not edit.\n";

// ---------- taxonomy ----------

const taxonomy = loadTaxonomy();
const topics = taxonomy.topics.map((t) => ({
  slug: t.slug,
  name: t.name,
  emoji: t.emoji ?? "•",
  group: t.group,
  impliedContext: t.implied_context ?? null,
}));
writeFileSync(
  "packages/shared/src/taxonomy.generated.ts",
  HEADER +
    `import type { TaxonomyTopic, TaxonomyContext } from "./taxonomy.ts";\n\n` +
    `export const TOPICS: TaxonomyTopic[] = ${JSON.stringify(topics, null, 2)};\n\n` +
    `export const CONTEXTS: TaxonomyContext[] = ${JSON.stringify(taxonomy.contexts.map((c) => ({ code: c.code, name: c.name, parent: c.parent ?? null })), null, 2)};\n`,
);

// ---------- demo bank ----------

const { files, schemaErrors } = loadFamilies();
if (schemaErrors.length) {
  console.error("Content has schema errors; run npm run content:validate");
  process.exit(1);
}

const perFile = files.map((f) =>
  f.families.flatMap((family) =>
    family.facts.flatMap((fact) =>
      fact.questions
        .filter((q) => q.status !== "RETIRED")
        .map((q) => ({
          id: q.id,
          familyId: family.family,
          text: q.text,
          options: q.options.map((o) => ({ key: o.key, text: o.text })),
          correctKey: q.options.find((o) => o.correct)!.key,
          explanation: q.explanation,
          ...(q.answer_time_override ? { answerMs: q.answer_time_override * 1000 } : {}),
        })),
    ),
  ),
);
const interleaved = [];
for (let i = 0; perFile.some((qs) => i < qs.length); i++) {
  for (const qs of perFile) if (qs[i]) interleaved.push(qs[i]);
}
writeFileSync(
  "packages/shared/src/demo-bank.generated.ts",
  HEADER +
    "// Includes unreviewed DRAFT questions (dev only).\n" +
    `import type { DemoQuestion } from "./demo-bank.ts";\n\n` +
    `export const DEMO_BANK: DemoQuestion[] = ${JSON.stringify(interleaved, null, 2)};\n`,
);

console.log(`Wrote ${topics.length} topics, ${taxonomy.contexts.length} contexts, ${interleaved.length} demo questions`);
