// Generates packages/shared/src/demo-bank.generated.ts from content/families — including DRAFTs.
// Dev-only stand-in for the Composition Engine (M4): questions are interleaved across files.
//   node scripts/dev/gen-demo-bank.ts
import { writeFileSync } from "node:fs";
import { loadFamilies } from "../content/lib/load.ts";

const { files, schemaErrors } = loadFamilies();
if (schemaErrors.length) {
  console.error("Content has schema errors; run npm run content:validate");
  process.exit(1);
}

const perFile = files.map((f) =>
  f.families.flatMap((family) =>
    family.facts.flatMap((fact) =>
      fact.questions
        .filter((q) => q.status !== "RETIRED")
        .map((q) => ({
          id: q.id,
          familyId: family.family,
          text: q.text,
          options: q.options.map((o) => ({ key: o.key, text: o.text })),
          correctKey: q.options.find((o) => o.correct)!.key,
          explanation: q.explanation,
          ...(q.answer_time_override ? { answerMs: q.answer_time_override * 1000 } : {}),
        })),
    ),
  ),
);

const interleaved = [];
for (let i = 0; perFile.some((qs) => i < qs.length); i++) {
  for (const qs of perFile) if (qs[i]) interleaved.push(qs[i]);
}

writeFileSync(
  "packages/shared/src/demo-bank.generated.ts",
  `// GENERATED by scripts/dev/gen-demo-bank.ts — do not edit. Includes unreviewed DRAFT questions (dev only).\n` +
    `import type { DemoQuestion } from "./demo-bank.ts";\n\n` +
    `export const DEMO_BANK: DemoQuestion[] = ${JSON.stringify(interleaved, null, 2)};\n`,
);
console.log(`Wrote ${interleaved.length} demo questions`);
