// Generates code in packages/shared from content/ so the worker and the web app share one source:
//   - taxonomy.generated.ts — topics and cultural contexts for onboarding and validation
//   - demo-bank.generated.ts — questions incl. DRAFTs, a dev-only stand-in for the Composition Engine (M4)
//
//   node scripts/dev/gen-shared.ts
import { writeFileSync } from "node:fs";
import { loadFamilies, loadTaxonomy } from "../content/lib/load.ts";

const HEADER = "// GENERATED by scripts/dev/gen-shared.ts — do not edit.\n";

// ---------- taxonomy ----------

const taxonomy = loadTaxonomy();
const topics = taxonomy.topics.map((t) => ({
  slug: t.slug,
  name: t.name,
  nameEn: t.name_en,
  emoji: t.emoji ?? "•",
  group: t.group,
  groupEn: t.group_en,
  impliedContext: t.implied_context ?? null,
  featured: t.level === "A",
}));
writeFileSync(
  "packages/shared/src/taxonomy.generated.ts",
  HEADER +
    `import type { TaxonomyTopic, TaxonomyContext } from "./taxonomy.ts";\n\n` +
    `export const TOPICS: TaxonomyTopic[] = ${JSON.stringify(topics, null, 2)};\n\n` +
    `export const CONTEXTS: TaxonomyContext[] = ${JSON.stringify(taxonomy.contexts.map((c) => ({ code: c.code, name: c.name, parent: c.parent ?? null })), null, 2)};\n`,
);

// ---------- bank ----------
// Includes unreviewed DRAFTs until C2: the engine filters them out unless config.allowDrafts.

const { files, schemaErrors } = loadFamilies();
if (schemaErrors.length) {
  console.error("Content has schema errors; run npm run content:validate");
  process.exit(1);
}

const bank = files.flatMap((f) =>
  f.families.flatMap((family) =>
    family.facts.flatMap((fact) =>
      fact.questions
        .filter((q) => q.status !== "RETIRED")
        .map((q) => ({
          id: q.id,
          factId: fact.id,
          familyId: family.family,
          language: q.language,
          originLanguage: q.origin_language,
          cultureSpecificity: q.culture_specificity,
          isBridge: q.is_bridge,
          text: q.text,
          options: q.options.map((o) => ({ key: o.key, text: o.text })),
          correctKey: q.options.find((o) => o.correct)!.key,
          explanation: q.explanation,
          topics: q.topics,
          contexts: q.contexts,
          generations: q.generations,
          difficulty: q.difficulty,
          dignity: q.dignity,
          effects: q.effects,
          ageSafety: q.age_safety,
          status: q.status,
          ...(q.answer_time_override ? { answerMs: q.answer_time_override * 1000 } : {}),
          ...(q.editor_rating ? { editorRating: q.editor_rating } : {}),
        })),
    ),
  ),
);
writeFileSync(
  "packages/shared/src/bank.generated.ts",
  HEADER + `import type { BankQuestion } from "./bank.ts";\n\n` + `export const BANK: BankQuestion[] = ${JSON.stringify(bank, null, 2)};\n`,
);

console.log(`Wrote ${topics.length} topics, ${taxonomy.contexts.length} contexts, ${bank.length} bank questions`);
